import type { Metadata } from 'next'
import './globals.css'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { ThemeProvider } from '@/components/theme-provider'
import Navbar from '@/components/web/navbar'
import { firaCode, fraunces, merriweatherSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Next 16',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-background text-foreground antialiased',
          merriweatherSans.variable,
          fraunces.variable,
          firaCode.variable,
        )}
      >
        <Navbar />
        {children}
        <TailwindIndicator />
      </body>
    </html>
  )
}
