import type { Metadata } from 'next'
import './globals.css'
import { ConvexClientProvider } from '@/components/base/convex-client-provider'
import { TailwindIndicator } from '@/components/base/tailwind-indicator'
import { ThemeProvider } from '@/components/base/theme-provider'
import { firaCode, fraunces, merriweatherSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Next 16',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'bg-background text-foreground antialiased',
          merriweatherSans.variable,
          fraunces.variable,
          firaCode.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>
            <main className="mx-auto w-full max-w-7xl px-4 md:px-6 lg:px-8">
              {children}
              <TailwindIndicator />
            </main>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
